<<<<<<< HEAD
project:
  type: website
  output-dir: docs  

website:
  title: "Estimación del Tiempo de Vuelo"
  navbar: false

format:
  html:
    toc: true
    theme: cosmo
    css: styles.css
=======
project:
  type: website
  output-dir: docs  

website:
  title: "Estimación del Tiempo de Vuelo"
  navbar: false

format:
  html:
    toc: true
    theme: cosmo
    css: styles.css
>>>>>>> 8d225f0a88014ea1c097de730917c19f36e90bb1
